export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const DEVICE_STATE_LISTENER = "DEVICE_STATE_LISTENER";

export const FETCH_CURR_PLAYBACK = "FETCH_CURR_PLAYBACK"
export const FETCH_SONG_ANALYSIS = "FETCH_SONG_ANALYSIS"
export const PLAY_STATE_ON = "PLAY_STATE_ON"
export const PLAY_STATE_OFF = "PLAY_STATE_OFF"

export const CURRENT_PROGRESS = "CURRENT_PROGRESS"
export const SEEK_PLAYER_PROGRESS = "SEEK_PLAYER_PROGRESS"

export const FETCH_AVAILABLE_DEVICES = "FETCH_AVAILABLE_DEVICES"

export const UPDATE_CURR_DEVICE_ID = "UPDATE_CURR_DEVICE_ID"

export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS"